// Every string a user reads in Build. Tested against the copy rules like the Start
// strings: no banned words, no emoji, headlines of six words or fewer, CTAs of four.

export const buildHome = {
  eyebrow: 'Build',
  headline: 'Your picture starts here',
  body: 'Profile first, then your bank, then confirm by exception. Only the documents the gaps name.',
  stepsLabel: 'The four steps',
  steps: {
    profile: { title: 'Your profile', body: 'About three minutes. Every answer decides what we ask later.' },
    connect: { title: 'Your bank', body: 'Twelve months of transactions, read once.' },
    confirm: { title: 'Confirm by exception', body: 'A handful of taps. We only ask what the bank cannot tell us.' },
    picture: { title: 'Your picture', body: 'A private document in the court’s own shape.' },
  },
  status: { done: 'Done', current: 'Now', later: 'Later' },
  next: {
    profileCta: 'Start your profile',
    profileBody: 'Your home, work, vehicles and pensions. The pension clock starts today.',
    connectCta: 'Connect your bank',
    connectBody: 'Profile done. Your bank fills in most of the picture before we ask anything.',
    confirmCta: 'Check what we found',
    confirmBody: 'Your bank is read. A few things to confirm, then the picture.',
    pictureCta: 'Open your picture',
    pictureBody: 'Every line evidenced, entered or explicitly none.',
  },
} as const

export const profile = {
  eyebrow: 'Profile · {n} of {total}',
  whyLabel: 'Why we ask',
  unlocksLabel: 'What it unlocks',
  continueCta: 'Continue',
  backCta: 'Back',
  chooseOne: 'Choose one option to continue.',
  enterAmount: 'Enter an amount in pounds.',
  enterDay: 'Enter a day of the month, 1 to 31.',
  summaryTitle: 'A few things to check',
  home: {
    headline: 'Your home',
    mortgage: {
      body: 'You told us you own your home with a mortgage. One question, so we can find the payment in your bank and name the statement to ask for.',
      legend: 'Who is your mortgage with?',
      hint: 'The lender on your statement.',
      why: 'The mortgage payment is one of the first things we look for in your bank.',
      unlocks: 'Section 2 of your picture, your home, and the mortgage statement task.',
    },
    rent: {
      body: 'You told us you rent. Three quick facts, so the payment is recognised when we see it.',
      legend: 'Who do you pay rent to?',
      options: { landlord: 'A private landlord', agent: 'A letting agent or housing association' },
      amount: 'How much each month?',
      day: 'Which day of the month?',
      why: 'Rent is your largest outgoing and the court asks for it.',
      unlocks: 'Section 2 of your picture and the housing line in your needs.',
    },
    lenders: [
      'Halifax', 'Nationwide', 'NatWest', 'Santander', 'Barclays', 'HSBC', 'Lloyds Bank', 'Virgin Money',
      'Coventry Building Society', 'Yorkshire Building Society', 'Skipton Building Society', 'Leeds Building Society',
      'TSB', 'The Co-operative Bank', 'Principality Building Society',
    ],
    otherLender: 'Another lender',
  },
  work: {
    headline: 'Your business',
    body: 'You told us you are self-employed or a director. Business income looks different in a bank account, so four short questions.',
    why: 'Salary, dividends and client payments each fill a different line of Form E.',
    unlocks: 'Section 9 of your picture, your business.',
    name: 'What is the business called?',
    structure: {
      legend: 'How is it set up?',
      options: { sole: 'Sole trader', ltd: 'Limited company', partnership: 'Partnership', other: 'Something else' },
    },
    pay: {
      legend: 'How do you pay yourself?',
      options: { paye: 'A PAYE salary only', dividends: 'Dividends only', both: 'Salary and dividends', drawings: 'Drawings', notSure: 'Not sure' },
    },
    channels: {
      legend: 'How else does money come in?',
      hint: 'Tick everything that applies.',
      options: { clients: 'Client payments', rental: 'Rent through the company', other: 'Something else', none: 'Nothing else' },
    },
  },
  vehicles: {
    headline: 'Your vehicles',
    body: 'Cars, vans and motorbikes. A vehicle on finance is both a debt and an asset.',
    why: 'Without this, a large regular payment could be mistaken for a car. With it, the finance is linked to the vehicle.',
    unlocks: 'Section 3 of your picture and the vehicle finance line in your debts.',
    count: {
      legend: 'How many vehicles do you own or pay for?',
      options: { none: 'None', one: 'One', more: 'More than one' },
    },
    finance: {
      legend: 'Is any of them on finance?',
      options: { yes: 'Yes', no: 'No' },
    },
    provider: { legend: 'Who is the finance with?' },
    providers: [
      'Black Horse', 'Santander Consumer Finance', 'Volkswagen Financial Services', 'BMW Financial Services',
      'Mercedes-Benz Financial Services', 'Toyota Financial Services', 'Ford Credit', 'Close Brothers Motor Finance',
      'Moneybarn', 'MotoNovo Finance', 'Startline Motor Finance', 'Blue Motor Finance',
    ],
    otherProvider: 'Another provider',
  },
  pensions: {
    headline: 'Your pensions',
    body: 'Pensions are the hardest part of any picture to evidence, and the slowest. This screen starts the clock.',
    why: 'Most workplace pensions are taken before pay reaches your bank, so only you can tell us they exist.',
    unlocks: 'Section 4 of your picture and your first task.',
    have: {
      legend: 'Do you have a pension?',
      options: {
        one: 'Yes, one',
        more: 'Yes, more than one',
        drawing: 'I am already drawing a pension',
        notSure: 'Not sure, maybe from old jobs',
        no: 'No',
      },
    },
    provider: { label: 'Who is it with?', hint: 'The name on your annual statement, if you know it. Leave blank if not.' },
    kind: {
      legend: 'Do any of these apply?',
      options: {
        publicSector: { title: 'I work, or worked, in the public sector', body: 'NHS, teachers, civil service, police, armed forces, local government' },
        largeCompany: { title: 'I joined a large company pension before 2012', body: '' },
        none: { title: 'None of these, or not sure', body: '' },
      },
    },
    cetv: {
      title: 'One thing to start today',
      body: 'Ask each pension provider for a cash equivalent transfer value. It is the figure a court uses. It takes 6 to 12 weeks to arrive, and public sector schemes can take up to 12 months. It becomes your first task.',
      term: 'cash equivalent transfer value',
      termBody: 'The CETV: what your pension would be worth if it were moved to another scheme today. Every pension in a settlement is valued this way.',
    },
  },
  children: {
    headline: 'Your children',
    body: 'Just the count for now. Names and ages come after your bank, when the picture can hold them.',
    why: 'Child Benefit in your bank confirms the count, so nothing is asked twice.',
    unlocks: 'Section 1 of your picture.',
    legend: 'You told us {n} under 18. Is that right?',
    options: { yes: 'Yes, {n}', no: 'No, a different number' },
    count: { legend: 'How many?', options: { '1': '1', '2': '2', '3': '3', '4+': '4 or more' } },
  },
  otherAssets: {
    headline: 'Anything else you own',
    body: 'Tick what applies. Anything left unticked is never asked about again.',
    why: 'Form E lists these one by one. Ticking here means we only ever ask about what exists.',
    unlocks: 'Sections 3 and 5 of your picture.',
    legend: 'Do you have any of these?',
    options: {
      savings: 'Savings',
      investments: 'Investments',
      crypto: 'Cryptocurrency',
      lifeInsurance: 'Life insurance with a cash value',
      valuables: 'Valuables worth more than £500',
      owed: 'Money someone owes you',
      none: 'None of these',
    },
  },
  accounts: {
    headline: 'Before you connect',
    body: 'Not a checklist, just a heads-up. Your picture is only as complete as the accounts behind it.',
    why: 'Form E needs every account, including any closed in the last 12 months.',
    unlocks: 'The bank connection.',
    items: [
      { title: 'App banks', body: 'Monzo, Starling, Revolut and Chase connect the same way as any other bank.' },
      { title: 'Savings with statements only', body: 'NS&I, Marcus, Chip and Atom cannot connect. A statement covers them.' },
      { title: 'Joint accounts', body: 'Connect them too. Either of you can, and they merge by sort code and account number.' },
      { title: 'Accounts closed in the last 12 months', body: 'The court still wants their statements. We will list them as a gap.' },
    ],
    cta: 'Continue',
  },
} as const

export const connect = {
  eyebrow: 'Your bank',
  headline: 'Connect your bank',
  body: 'Twelve months of transactions, read once, so the picture is drafted before we ask you anything.',
  trustLabel: 'Through Tink',
  trust: ['FCA regulated', 'Read-only, we cannot move money', 'Disconnect anytime'],
  banksLegend: 'Choose your bank',
  banks: [
    { id: 'barclays', name: 'Barclays' },
    { id: 'hsbc', name: 'HSBC' },
    { id: 'lloyds', name: 'Lloyds' },
    { id: 'natwest', name: 'NatWest' },
    { id: 'santander', name: 'Santander' },
    { id: 'nationwide', name: 'Nationwide' },
    { id: 'monzo', name: 'Monzo' },
    { id: 'starling', name: 'Starling' },
  ],
  searchCta: 'Search all providers',
  searchBody: 'Every UK bank and building society that supports Open Banking.',
  notHereTitle: 'My bank is not here',
  notHereBody: 'A statement upload and manual entry arrive with the document uploads. Until then, a test scenario shows the whole journey.',
  scenarioTitle: 'Or try a test scenario',
  scenarioBody: 'Five synthetic households, each with twelve months of realistic transactions. Nothing here is real.',
  scenarioLegend: 'Test scenarios',
  unavailable: 'Bank connection is not switched on in this preview. Choose a test scenario to see the journey.',
  failed: 'The bank connection did not complete and nothing was saved. Try again, choose another bank, or use a test scenario.',
  cancelled: 'You came back without connecting. Nothing has changed.',
  connectedTitle: 'Connected',
  connectedBody: '{accounts} from {provider}, {months} months of transactions.',
  oneAccount: '1 account',
  manyAccounts: '{n} accounts',
  continueCta: 'See what we found',
  disconnectCta: 'Disconnect and clear',
  multiple: 'Most people have three to five accounts. Connect another once this one is in the picture.',
} as const

export const reveal = {
  eyebrow: 'Your bank',
  headline: 'What your bank shows',
  body: 'Twelve months of {provider}, read in one pass. Nothing here is final. The next screen checks it with you.',
  progressLabel: 'Reading your accounts',
  accountLabel: '{provider} ending {last4}',
  items: {
    incomeNone: 'No regular income visible in this account.',
    salary: 'Salary',
    childBenefit: 'Child Benefit',
    benefits: 'Benefits',
    pensionIncome: 'Pension income',
    selfEmployment: 'Business income',
    mortgage: 'Mortgage',
    rent: 'Rent',
    councilTax: 'Council tax',
    pension: 'Pension contributions',
    insurance: 'Insurance',
    utilities: 'Utilities',
    childcare: 'Childcare',
    loan: 'Loan or finance',
    creditCard: 'Credit card',
    investment: 'Investments',
    transactions: 'Transactions read',
  },
  perMonth: '£{amount} a month',
  fromPayee: '£{amount} a month, {payee}',
  childrenMatch: 'matches the {n} children you told us about',
  childrenMismatch: 'suggests {n}; you told us {declared}',
  count: '{n} over {months} months',
  continueCta: 'Check these with me',
} as const

export const confirm = {
  tier1: {
    eyebrow: 'Confirm by exception',
    headline: 'Here is what we found',
    body: 'Each line comes straight from your bank, so we have taken it as read. Tap Not right? on anything that is wrong. Otherwise, carry on.',
    notRight: 'Not right?',
    source: 'From {source}',
    andProfile: 'and your profile',
    continueCta: 'Continue',
    remaining: '{n} quick checks follow.',
    remainingOne: '1 quick check follows.',
    remainingNone: 'Nothing else to check.',
  },
  tier2: { eyebrow: 'Quick check' },
  tier3: { eyebrow: 'One question' },
  question: {
    progress: 'Check {n} of {total}',
    whyLabel: 'Why we ask',
    evidenceLabel: 'What the bank shows',
    continueCta: 'Continue',
    skipCta: 'Skip for now',
    notMine: 'This is not mine',
    notMineBody: 'It will be removed from your picture.',
    escape: 'You can change any answer later from your picture.',
    chooseOne: 'Choose one option, or skip.',
  },
  gaps: {
    eyebrow: 'What the bank cannot see',
    headline: 'Documents that fill the gaps',
    body: 'Your bank proves the payments. These documents prove the balances behind them. Nothing is needed today. The pension letter simply takes longest, so it comes first.',
    whatLabel: 'What',
    fromLabel: 'From',
    whyLabel: 'Why',
    howLongLabel: 'How long',
    helpLabel: 'How to get it',
    requested: 'Already requested',
    skipCta: 'Skip for now',
    none: 'Nothing is missing that a document could fill.',
    picture: 'Each gap stays on your picture until a document fills it.',
  },
  values: {
    confirmed: 'Confirmed',
    notRight: 'Not right',
    skipped: 'Skipped',
    notMine: 'Removed',
    requested: 'Requested',
  },
} as const

export const findingEvidence = {
  payments: '{n} payments, {frequency}',
  credits: '{n} credits, {frequency}',
} as const

export const findings = {
  // Tier 1 lines and the question each carries behind "Not right?".
  salary: {
    line: 'Salary: £{amount} a month from {payee}',
    evidence: '{n} credits, {variation}% variation',
    question: 'Is £{amount} a month from {payee} your salary?',
    why: 'Take-home pay is the first line of Form E section 2.15, and payslips will need to match it.',
    options: { yes: 'Yes, that is my salary', other: 'No, it is something else' },
  },
  childBenefit: {
    line: 'Child Benefit: £{amount} a month from HMRC',
    match: 'Matches the {n} children you told us about',
    mismatch: 'Suggests {n}; you told us {declared}',
    question: 'Is £{amount} a month from HMRC your Child Benefit?',
    why: 'Benefits sit in Form E section 2.20, and the amount confirms the number of children.',
    options: { yes: 'Yes', other: 'No, it is a different benefit' },
  },
  dwp: {
    line: 'Benefit: £{amount} a month from DWP',
    question: '£{amount} a month from DWP. Which benefit is it?',
    why: 'Each benefit is its own line in Form E section 2.20.',
    options: { uc: 'Universal Credit', pip: 'Personal Independence Payment', esa: 'Employment and Support Allowance', statePension: 'State Pension', other: 'Something else' },
  },
  selfEmployment: {
    line: 'Business income: £{amount} a month from {payee}',
    question: '£{amount} a month from {payee}. What is this?',
    matchesProfile: 'Matches the business you described',
    why: 'Business income fills Form E section 2.16, and the structure decides which accounts we ask for.',
    options: { sole: 'Sole trader income', ltd: 'Limited company income', partnership: 'Partnership income', employment: 'Employment, actually', other: 'Something else' },
  },
  noIncome: {
    question: 'We cannot see regular income in this account. What is your situation?',
    why: 'Form E asks for income from every source, even if it arrives elsewhere.',
    options: { otherAccount: 'Paid into another account', selfEmployed: 'Self-employed, paid irregularly', notWorking: 'Not working at the moment', retired: 'Retired', carer: 'Caring for someone', other: 'Something else' },
  },
  mortgage: {
    line: 'Mortgage: £{amount} a month to {payee}',
    matchesLender: 'Matches the lender you named',
    question: 'Is £{amount} a month to {payee} your mortgage?',
    why: 'The mortgage is Form E section 2.1, and the statement behind it is the first document to fetch.',
    options: { yes: 'Yes, my mortgage', other: 'No, it is something else' },
  },
  rent: {
    line: 'Rent: £{amount} a month to {payee}',
    matchesProfile: 'Matches the rent you told us about',
    question: 'Is £{amount} a month to {payee} your rent?',
    why: 'Rent is your housing cost in Form E section 3.1.',
    options: { yes: 'Yes, my rent', other: 'No, it is something else' },
  },
  noHousing: {
    question: 'We cannot see a mortgage, rent or council tax. Where do you live?',
    why: 'Your home is Form E section 2.1, whoever pays for it.',
    options: { outright: 'A home we own outright', partnerPays: 'My partner pays the housing costs', family: 'With family or friends', otherAccount: 'It is paid from another account', other: 'Something else' },
  },
  councilTax: {
    line: 'Council tax: £{amount} a month to {payee}',
    question: 'Is £{amount} a month to {payee} your council tax?',
    why: 'Council tax is a housing cost in Form E section 3.1.',
    options: { yes: 'Yes', other: 'No, it is something else' },
  },
  pension: {
    line: 'Pension contributions: £{amount} a month to {payee}',
    matchesProvider: 'Matches the provider you named',
    question: '£{amount} a month to {payee}. Pension or insurance?',
    hint: 'You told us your pension is with {provider}.',
    why: 'Aviva and others sell both. A pension is an asset in Form E section 2.13; insurance is an outgoing.',
    options: { pension: 'Pension', insurance: 'Insurance', unsure: 'Not sure' },
  },
  noPension: {
    question: 'We cannot see pension contributions. That is normal. Which of these is true?',
    why: 'Workplace pensions usually leave your pay before it reaches the bank, so only you can tell us.',
    options: { workplace: 'I have a workplace pension', personal: 'I have a personal pension', multiple: 'More than one', drawing: 'I am drawing a pension', unsure: 'Not sure', none: 'No pension' },
  },
  investment: {
    line: 'Investments: £{amount} a month to {payee}',
    question: '£{amount} a month to {payee}. What is it?',
    why: 'Savings and investments are Form E sections 2.3 and 2.4, and the statement gives the value.',
    options: { savings: 'A savings account', isa: 'An ISA', investment: 'An investment account', sipp: 'A pension', crypto: 'Cryptocurrency', closed: 'Closed now', other: 'Something else' },
  },
  creditCard: {
    line: 'Credit card: £{amount} a month to {payee}',
    question: 'Is £{amount} a month to {payee} a credit card payment?',
    why: 'Card balances are debts in Form E section 2.14.',
    options: { yes: 'Yes, a credit card', other: 'No, it is something else' },
  },
  loan: {
    line: 'Loan or finance: £{amount} a month to {payee}',
    question: '£{amount} a month to {payee}. What is this loan?',
    hintVehicle: 'You told us about a vehicle on finance with {provider}.',
    matchesProvider: 'Matches the finance provider you named',
    why: 'Loans are debts in Form E section 2.14; car finance also links to the vehicle.',
    options: { carFinance: 'Car finance', personal: 'A personal loan', student: 'A student loan', secured: 'A loan secured on the home', other: 'Something else' },
  },
  bnpl: {
    line: 'Buy now, pay later: £{amount} a month to {payee}',
    question: 'Is £{amount} a month to {payee} a buy now, pay later plan?',
    why: 'Instalment balances are debts in Form E section 2.14.',
    options: { yes: 'Yes', other: 'No, it is something else' },
  },
} as const

export const gaps = {
  cetv: {
    what: 'A cash equivalent transfer value letter',
    from: '{provider}',
    fromUnknown: 'each pension provider',
    why: 'The court values every pension this way. Without it the pension is a guess.',
    howLong: '6 to 12 weeks. Public sector schemes can take up to 12 months.',
    help: 'Ask in writing today. The first request each year is usually free.',
    mccloud: 'Public sector schemes are still working through the McCloud remedy, which can slow things further.',
  },
  valuation: {
    what: 'A valuation of your home',
    from: 'Three estate agents, or a RICS surveyor',
    why: 'Your home is usually the largest figure in the picture.',
    howLong: '1 to 2 weeks',
    help: 'Free agent valuations are fine at this stage. Keep the emails.',
  },
  mortgageStatement: {
    what: 'Your latest mortgage statement',
    from: '{lender}',
    why: 'It shows the balance, the rate and the term. The bank only shows the payment.',
    howLong: '1 to 3 days',
    help: 'Most lenders show it in their app. Download the PDF.',
  },
  payslips: {
    what: 'Your last three payslips',
    from: '{employer}',
    why: 'They show gross pay, tax and pension deductions the bank never sees.',
    howLong: 'To hand',
    help: 'Your payroll portal or the paper copies.',
  },
  cardStatement: {
    what: 'The latest statement',
    from: '{provider}',
    why: 'The bank shows the payment. The statement shows the balance and the rate.',
    howLong: 'To hand',
    help: 'In the provider’s app, under statements.',
  },
  accountStatement: {
    what: 'The latest statement',
    from: '{provider}',
    fromDeclared: { savings: 'Your savings provider', investments: 'Your investment platform', crypto: 'Your exchange or wallet' },
    why: 'The bank shows money going in. The statement shows what it is worth now.',
    howLong: 'To hand',
    help: 'In the provider’s app or by post.',
  },
} as const

export const picture = {
  eyebrow: 'Build · private',
  headline: 'Your picture',
  lede: 'A private record of what you own, owe, earn and spend, in the court’s own shape. Every line is evidenced, entered, or explicitly none.',
  updated: 'Last updated {when}',
  chaptersLabel: 'Chapters',
  chapters: {
    children: 'Children',
    home: 'Home',
    property: 'Property and valuables',
    pensions: 'Pensions',
    savings: 'Savings',
    debts: 'Debts',
    income: 'Income',
    spending: 'Spending',
    business: 'Business',
    needs: 'Needs',
  },
  sections: {
    children: 'The children',
    home: 'Your home',
    property: 'Other property and valuables',
    pensions: 'Your pensions',
    savings: 'Savings and investments',
    debts: 'Your debts',
    income: 'Your income',
    spending: 'Your spending',
    business: 'Your business',
    needs: 'Your needs',
  },
  formE: 'Form E {field}',
  status: { complete: 'Complete', attention: 'Needs attention', empty: 'Nothing yet', none: 'Explicitly none' },
  evidence: {
    proved: 'Proved',
    inferred: 'Inferred',
    gap: 'Gap',
    invisible: 'Only you can say',
  },
  evidenceBody: {
    proved: 'Your bank shows this on its own.',
    inferred: 'Your bank suggested it and you confirmed it.',
    gap: 'A document can prove this. The bank cannot.',
    invisible: 'Only you can tell us this.',
  },
  trust: {
    'self-declared': 'You told us',
    'bank-evidenced': 'Verified from {source}',
    'credit-verified': 'Credit-verified',
    'document-evidenced': 'From a document',
    'both-party-agreed': 'Agreed by both',
    'court-sealed': 'Court-sealed',
  },
  estimated: 'Estimated',
  known: 'Known',
  unknown: 'Not yet known',
  notEntered: 'Not yet entered',
  none: 'None',
  perMonth: 'a month',
  toConfirm: '{n} to confirm',
  removed: 'Removed by you',
  snapshot: {
    title: 'Snapshot',
    netWorth: 'Net worth',
    netWorthBody: 'What you own minus what you owe, where a value is known',
    assets: 'Assets',
    debts: 'Debts',
    monthlyGap: 'Monthly gap',
    monthlyGapBody: 'Income after outgoings, each month',
    income: 'Income',
    outgoings: 'Outgoings',
    withoutValue: '{n} lines have no value yet',
    readiness: 'Readiness',
  },
  readiness: {
    sketch: 'Not yet ready for a first conversation',
    draft: 'Ready for a first conversation',
    evidenced: 'Ready to share, some items outstanding',
    complete: 'Complete',
  },
  fidelity: { sketch: 'Sketch', draft: 'Draft', evidenced: 'Evidenced', locked: 'Locked' },
  sources: {
    title: 'Data sources',
    bank: '{provider} ending {last4}',
    bankNoLast4: '{provider} account',
    months: '{n} months, {t} transactions',
    profile: 'Your profile and interview answers',
    scenario: 'Test scenario',
  },
  attention: {
    title: 'Needs attention',
    none: 'Nothing waiting on you.',
    gap: 'Waiting for a document',
    unconfirmed: 'Skipped, still to confirm',
    review: 'Review',
  },
  history: {
    title: 'History',
    empty: 'No changes yet.',
    change: 'Change',
    bankConnected: 'Bank connected: {provider}',
    profile: 'Profile completed',
    confirmed: 'Confirmed: {line}',
    answered: 'Answered: {line}',
    skipped: 'Skipped: {line}',
    removed: 'Removed: {line}',
    requested: 'Requested: {what} from {from}',
  },
  lines: {
    childrenCount: 'Children under 18',
    childrenNone: 'No children under 18.',
    childrenNames: 'Names and ages',
    childBenefitMatch: 'Child Benefit from HMRC matches this count',
    childBenefitMismatch: 'Child Benefit from HMRC suggests {n}',
    tenure: 'How you hold your home',
    tenureValues: { mortgage: 'Owned with a mortgage', outright: 'Owned outright', rent: 'Rented', other: 'Another arrangement' },
    mortgagePayment: 'Mortgage payment',
    mortgageBalance: 'Mortgage balance',
    homeValue: 'Value of your home',
    rentPayment: 'Rent',
    landlord: 'Paid to',
    landlordValues: { landlord: 'A private landlord', agent: 'A letting agent or housing association' },
    vehicles: 'Vehicles',
    vehiclesValues: { none: 'None', one: 'One vehicle', more: 'More than one vehicle' },
    vehicleFinance: 'Vehicle finance',
    vehicleFinanceUnnamed: 'On finance, provider not named',
    vehicleValue: 'Vehicle value',
    propertyNone: 'No vehicles, valuables or money owed to you, as you told us.',
    valuables: 'Valuables over £500',
    owed: 'Money owed to you',
    lifeInsurance: 'Life insurance',
    pensionsNone: 'No pension, as you told us, and none visible in your bank.',
    pensionDeclared: 'Pensions',
    pensionDeclaredValues: { one: 'One pension', more: 'More than one pension', drawing: 'A pension in payment', notSure: 'Possibly, from old jobs', no: 'None' },
    pensionProvider: 'Provider',
    pensionKind: 'Scheme type',
    pensionKindValues: { publicSector: 'Public sector, likely defined benefit', largeCompany: 'Large company, possibly defined benefit', none: 'Not known yet' },
    pensionContribution: 'Contributions',
    cetv: 'Transfer value',
    cetvRequested: 'Requested {when}. Allow 6 to 12 weeks.',
    account: '{provider} account',
    balance: 'Balance',
    savingsNone: 'No savings or investments visible in your bank, and none declared.',
    savingsDeclared: 'Savings',
    investmentsDeclared: 'Investments',
    crypto: 'Cryptocurrency',
    paidIn: 'Paid in',
    value: 'Value',
    creditCard: 'Credit card',
    loan: 'Loan',
    bnpl: 'Buy now, pay later',
    debtsNone: 'None visible in your bank and none declared.',
    incomeNone: 'No regular income visible in this account.',
    salary: 'Salary',
    childBenefit: 'Child Benefit',
    benefit: 'Benefit',
    pensionIncome: 'Pension income',
    businessIncome: 'Business income',
    otherIncome: 'Other income',
    incomeTotal: 'Total income',
    spendingTotal: 'Total outgoings',
    transactions: '{n} transactions',
    businessNone: 'You told us you are employed, not self-employed or a director.',
    businessName: 'Business',
    businessStructure: 'Structure',
    businessStructureValues: { sole: 'Sole trader', ltd: 'Limited company', partnership: 'Partnership', other: 'Other' },
    businessPay: 'How you are paid',
    businessPayValues: { paye: 'PAYE salary', dividends: 'Dividends', both: 'Salary and dividends', drawings: 'Drawings', notSure: 'Not sure yet' },
    businessValue: 'Business value',
    directorsLoan: 'Director’s loan account',
    needsLocked: 'Opens once the picture is a draft.',
    needsNow: 'Outgoings today, from your bank',
    needsBody: 'Your monthly gap is the starting point. Future needs are set out at Settle.',
  },
  categories: {
    mortgage: 'Mortgage',
    rent: 'Rent',
    council_tax: 'Council tax',
    utilities: 'Utilities',
    insurance: 'Insurance',
    pension_contribution: 'Pension contributions',
    childcare: 'Childcare',
    loan_repayment: 'Loan repayments',
    child_maintenance: 'Child maintenance',
    credit_card: 'Credit card payments',
    investment: 'Savings and investments',
    subscription: 'Subscriptions and phones',
    groceries: 'Groceries',
    dining: 'Eating out',
    fuel: 'Fuel',
    transport: 'Transport',
    education: 'School and education',
    healthcare: 'Health',
    gambling: 'Other',
    unknown: 'Uncategorised',
  },
  private: 'Private. Nothing here is shared until you choose to share it, and the share is a separate step.',
  nextStep: {
    cetv: 'Ask for your CETV',
    valuation: 'Get your home valued',
    mortgageStatement: 'Download your mortgage statement',
    payslips: 'Find your last payslips',
    cardStatement: 'Find the card statement',
    accountStatement: 'Find the latest statement',
    none: 'Share, when it feels ready',
  },
} as const

export const errors = {
  noSession: 'Sign in to continue.',
  noBank: 'Connect a bank or choose a test scenario first.',
  noProfile: 'Your profile comes first.',
} as const
