// Structured output schemas for document extraction
// These schemas constrain the AI response to guaranteed valid JSON
// Document-type-specific: each document type has its own extraction shape
//
// DESIGN: AI extracts pure financial facts. Clarification questions, gap
// detection, and user-facing text are generated by app code using the
// spec 13 decision trees. This keeps output tokens low (~350 vs ~1000)
// and makes questions deterministic and easy to iterate on.

// ═══ Shared types ═══

export interface ExtractedIncome {
  source: string
  amount: number
  period: 'monthly' | 'annual'
  confidence: number
  type: 'employment' | 'benefits' | 'rental' | 'self_employment' | 'pension_income' | 'maintenance' | 'other'
}

export interface DetectedPayment {
  payee: string
  amount: number
  frequency: 'monthly' | 'weekly' | 'quarterly' | 'annual' | 'one_off'
  confidence: number
  likely_category: 'mortgage' | 'rent' | 'insurance' | 'pension_contribution' | 'childcare' | 'loan_repayment' | 'child_maintenance' | 'utilities' | 'council_tax' | 'subscription' | 'credit_card' | 'investment' | 'gambling' | 'groceries' | 'dining' | 'fuel' | 'transport' | 'education' | 'healthcare' | 'unknown'
}

export interface SpendingCategory {
  category: string
  monthly_average: number
  transaction_count: number
}

// ═══ Bank statement extraction ═══

export interface BankStatementExtraction {
  document_type: 'bank_statement'
  provider: string
  account_number_last4: string | null
  account_type: 'current' | 'savings' | 'joint_current' | 'joint_savings' | 'unknown'
  is_joint: boolean
  joint_holder_name: string | null
  statement_period_start: string | null
  statement_period_end: string | null
  closing_balance: number | null
  income_deposits: ExtractedIncome[]
  regular_payments: DetectedPayment[]
  spending_categories: SpendingCategory[]
  notable_transactions: {
    description: string
    amount: number
    date: string | null
    reason_flagged: string
  }[]
}

export const BANK_STATEMENT_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: { type: 'string' as const, enum: ['bank_statement'] },
    provider: { type: 'string' as const },
    account_number_last4: { type: ['string', 'null'] as const },
    account_type: { type: 'string' as const, enum: ['current', 'savings', 'joint_current', 'joint_savings', 'unknown'] },
    is_joint: { type: 'boolean' as const },
    joint_holder_name: { type: ['string', 'null'] as const },
    statement_period_start: { type: ['string', 'null'] as const },
    statement_period_end: { type: ['string', 'null'] as const },
    closing_balance: { type: ['number', 'null'] as const },
    income_deposits: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
        additionalProperties: false as const,
        properties: {
          source: { type: 'string' as const },
          amount: { type: 'number' as const },
          period: { type: 'string' as const, enum: ['monthly', 'annual'] },
          confidence: { type: 'number' as const },
          type: { type: 'string' as const, enum: ['employment', 'benefits', 'rental', 'self_employment', 'pension_income', 'maintenance', 'other'] },
        },
        required: ['source', 'amount', 'period', 'confidence', 'type'],
      },
    },
    regular_payments: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
        additionalProperties: false as const,
        properties: {
          payee: { type: 'string' as const },
          amount: { type: 'number' as const },
          frequency: { type: 'string' as const, enum: ['monthly', 'weekly', 'quarterly', 'annual', 'one_off'] },
          confidence: { type: 'number' as const },
          likely_category: { type: 'string' as const, enum: ['mortgage', 'rent', 'insurance', 'pension_contribution', 'childcare', 'loan_repayment', 'child_maintenance', 'utilities', 'council_tax', 'subscription', 'credit_card', 'investment', 'gambling', 'groceries', 'dining', 'fuel', 'transport', 'education', 'healthcare', 'unknown'] },
        },
        required: ['payee', 'amount', 'frequency', 'confidence', 'likely_category'],
      },
    },
    spending_categories: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
  additionalProperties: false as const,
        properties: {
          category: { type: 'string' as const },
          monthly_average: { type: 'number' as const },
          transaction_count: { type: 'number' as const },
        },
        required: ['category', 'monthly_average', 'transaction_count'],
      },
    },
    notable_transactions: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
  additionalProperties: false as const,
        properties: {
          description: { type: 'string' as const },
          amount: { type: 'number' as const },
          date: { type: ['string', 'null'] as const },
          reason_flagged: { type: 'string' as const },
        },
        required: ['description', 'amount', 'reason_flagged'],
      },
    },
  },
  required: ['document_type', 'provider', 'account_type', 'is_joint', 'income_deposits', 'regular_payments', 'spending_categories', 'notable_transactions'],
}

// ═══ Payslip extraction ═══

export interface PayslipExtraction {
  document_type: 'payslip'
  employer: string
  pay_period: string | null
  pay_date: string | null
  gross_pay: number
  net_pay: number
  tax_deducted: number
  tax_code: string | null
  national_insurance: number
  pension_contribution: number | null
  student_loan: number | null
  other_deductions: { label: string; amount: number }[]
  ytd_gross: number | null
  ytd_tax: number | null
  overtime_or_commission: number | null
  is_overtime_regular: boolean | null
}

export const PAYSLIP_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: { type: 'string' as const, enum: ['payslip'] },
    employer: { type: 'string' as const },
    pay_period: { type: ['string', 'null'] as const },
    pay_date: { type: ['string', 'null'] as const },
    gross_pay: { type: 'number' as const },
    net_pay: { type: 'number' as const },
    tax_deducted: { type: 'number' as const },
    tax_code: { type: ['string', 'null'] as const },
    national_insurance: { type: 'number' as const },
    pension_contribution: { type: ['number', 'null'] as const },
    student_loan: { type: ['number', 'null'] as const },
    other_deductions: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
  additionalProperties: false as const,
        properties: {
          label: { type: 'string' as const },
          amount: { type: 'number' as const },
        },
        required: ['label', 'amount'],
      },
    },
    ytd_gross: { type: ['number', 'null'] as const },
    ytd_tax: { type: ['number', 'null'] as const },
    overtime_or_commission: { type: ['number', 'null'] as const },
    is_overtime_regular: { type: ['boolean', 'null'] as const },
  },
  required: ['document_type', 'employer', 'gross_pay', 'net_pay', 'tax_deducted', 'national_insurance', 'other_deductions'],
}

// ═══ Mortgage statement extraction ═══

export interface MortgageStatementExtraction {
  document_type: 'mortgage_statement'
  lender: string
  property_address: string | null
  account_holders: string[]
  is_joint: boolean
  outstanding_balance: number
  monthly_payment: number
  interest_rate: number | null
  rate_type: 'fixed' | 'variable' | 'tracker' | 'unknown'
  mortgage_type: 'repayment' | 'interest_only' | 'part_and_part' | 'unknown'
  term_end_date: string | null
  early_repayment_charge: number | null
  erc_end_date: string | null
  arrears: number | null
  multiple_parts: boolean
  parts: { balance: number; rate: number; type: string }[]
}

export const MORTGAGE_STATEMENT_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: { type: 'string' as const, enum: ['mortgage_statement'] },
    lender: { type: 'string' as const },
    property_address: { type: ['string', 'null'] as const },
    account_holders: { type: 'array' as const, items: { type: 'string' as const } },
    is_joint: { type: 'boolean' as const },
    outstanding_balance: { type: 'number' as const },
    monthly_payment: { type: 'number' as const },
    interest_rate: { type: ['number', 'null'] as const },
    rate_type: { type: 'string' as const, enum: ['fixed', 'variable', 'tracker', 'unknown'] },
    mortgage_type: { type: 'string' as const, enum: ['repayment', 'interest_only', 'part_and_part', 'unknown'] },
    term_end_date: { type: ['string', 'null'] as const },
    early_repayment_charge: { type: ['number', 'null'] as const },
    erc_end_date: { type: ['string', 'null'] as const },
    arrears: { type: ['number', 'null'] as const },
    multiple_parts: { type: 'boolean' as const },
    parts: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
  additionalProperties: false as const,
        properties: {
          balance: { type: 'number' as const },
          rate: { type: 'number' as const },
          type: { type: 'string' as const },
        },
        required: ['balance', 'rate', 'type'],
      },
    },
  },
  required: ['document_type', 'lender', 'is_joint', 'outstanding_balance', 'monthly_payment', 'multiple_parts', 'parts'],
}

// ═══ Pension CETV letter extraction ═══

export interface PensionCETVExtraction {
  document_type: 'pension_cetv'
  scheme_name: string
  provider: string
  pension_type: 'defined_benefit' | 'defined_contribution' | 'sipp' | 'unknown'
  cetv_value: number
  cetv_date: string | null
  annual_pension_at_retirement: number | null
  retirement_age: number | null
  membership_start_date: string | null
  membership_end_date: string | null
  is_public_sector: boolean
  scheme_type_name: string | null
}

export const PENSION_CETV_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: { type: 'string' as const, enum: ['pension_cetv'] },
    scheme_name: { type: 'string' as const },
    provider: { type: 'string' as const },
    pension_type: { type: 'string' as const, enum: ['defined_benefit', 'defined_contribution', 'sipp', 'unknown'] },
    cetv_value: { type: 'number' as const },
    cetv_date: { type: ['string', 'null'] as const },
    annual_pension_at_retirement: { type: ['number', 'null'] as const },
    retirement_age: { type: ['number', 'null'] as const },
    membership_start_date: { type: ['string', 'null'] as const },
    membership_end_date: { type: ['string', 'null'] as const },
    is_public_sector: { type: 'boolean' as const },
    scheme_type_name: { type: ['string', 'null'] as const },
  },
  required: ['document_type', 'scheme_name', 'provider', 'pension_type', 'cetv_value', 'is_public_sector'],
}

// ═══ Savings / investment statement extraction ═══

export interface SavingsStatementExtraction {
  document_type: 'savings_statement'
  provider: string
  account_type: 'savings' | 'cash_isa' | 'stocks_and_shares_isa' | 'lifetime_isa' | 'investment_fund' | 'premium_bonds' | 'other'
  account_holder: string | null
  is_joint: boolean
  current_balance: number
  interest_rate: number | null
  large_recent_withdrawals: { date: string | null; amount: number; description: string }[]
}

export const SAVINGS_STATEMENT_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: { type: 'string' as const, enum: ['savings_statement'] },
    provider: { type: 'string' as const },
    account_type: { type: 'string' as const, enum: ['savings', 'cash_isa', 'stocks_and_shares_isa', 'lifetime_isa', 'investment_fund', 'premium_bonds', 'other'] },
    account_holder: { type: ['string', 'null'] as const },
    is_joint: { type: 'boolean' as const },
    current_balance: { type: 'number' as const },
    interest_rate: { type: ['number', 'null'] as const },
    large_recent_withdrawals: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
  additionalProperties: false as const,
        properties: {
          date: { type: ['string', 'null'] as const },
          amount: { type: 'number' as const },
          description: { type: 'string' as const },
        },
        required: ['amount', 'description'],
      },
    },
  },
  required: ['document_type', 'provider', 'account_type', 'is_joint', 'current_balance', 'large_recent_withdrawals'],
}

// ═══ Credit card statement extraction ═══

export interface CreditCardStatementExtraction {
  document_type: 'credit_card_statement'
  provider: string
  account_holder: string | null
  is_joint: boolean
  outstanding_balance: number
  credit_limit: number | null
  minimum_payment: number | null
  interest_rate_apr: number | null
  notable_transactions: { description: string; amount: number; reason_flagged: string }[]
}

export const CREDIT_CARD_STATEMENT_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: { type: 'string' as const, enum: ['credit_card_statement'] },
    provider: { type: 'string' as const },
    account_holder: { type: ['string', 'null'] as const },
    is_joint: { type: 'boolean' as const },
    outstanding_balance: { type: 'number' as const },
    credit_limit: { type: ['number', 'null'] as const },
    minimum_payment: { type: ['number', 'null'] as const },
    interest_rate_apr: { type: ['number', 'null'] as const },
    notable_transactions: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
  additionalProperties: false as const,
        properties: {
          description: { type: 'string' as const },
          amount: { type: 'number' as const },
          reason_flagged: { type: 'string' as const },
        },
        required: ['description', 'amount', 'reason_flagged'],
      },
    },
  },
  required: ['document_type', 'provider', 'is_joint', 'outstanding_balance', 'notable_transactions'],
}

// ═══ P60 / Tax return extraction ═══

export interface P60Extraction {
  document_type: 'p60' | 'tax_return'
  employer_or_source: string
  tax_year: string | null
  total_pay: number
  total_tax_deducted: number
  total_ni: number | null
  self_employment_profit: number | null
  dividend_income: number | null
  rental_income: number | null
  other_income: { source: string; amount: number }[]
}

export const P60_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: { type: 'string' as const, enum: ['p60', 'tax_return'] },
    employer_or_source: { type: 'string' as const },
    tax_year: { type: ['string', 'null'] as const },
    total_pay: { type: 'number' as const },
    total_tax_deducted: { type: 'number' as const },
    total_ni: { type: ['number', 'null'] as const },
    self_employment_profit: { type: ['number', 'null'] as const },
    dividend_income: { type: ['number', 'null'] as const },
    rental_income: { type: ['number', 'null'] as const },
    other_income: {
      type: 'array' as const,
      items: {
        type: 'object' as const,
  additionalProperties: false as const,
        properties: {
          source: { type: 'string' as const },
          amount: { type: 'number' as const },
        },
        required: ['source', 'amount'],
      },
    },
  },
  required: ['document_type', 'employer_or_source', 'total_pay', 'total_tax_deducted', 'other_income'],
}

// ═══ Document classification ═══

export interface DocumentClassification {
  document_type: 'bank_statement' | 'payslip' | 'mortgage_statement' | 'pension_cetv' | 'savings_statement' | 'credit_card_statement' | 'tax_return' | 'p60' | 'business_accounts' | 'property_valuation' | 'unknown'
  confidence: number
  provider: string | null
  description: string
}

export const CLASSIFICATION_SCHEMA = {
  type: 'object' as const,
  additionalProperties: false as const,
  properties: {
    document_type: {
      type: 'string' as const,
      enum: ['bank_statement', 'payslip', 'mortgage_statement', 'pension_cetv', 'savings_statement', 'credit_card_statement', 'tax_return', 'p60', 'business_accounts', 'property_valuation', 'unknown'],
    },
    confidence: { type: 'number' as const },
    provider: { type: ['string', 'null'] as const },
    description: { type: 'string' as const },
  },
  required: ['document_type', 'confidence', 'description'],
}
